
// vscodeの拡張機能rest clientを利用する

POST http://localhost/LittleHoodAdvServer/API/loginUser HTTP/1.1
content-type: application/x-www-form-urlencoded

userName=test

###

POST http://localhost/LittleHoodAdvServer/API/createUser HTTP/1.1
content-type: application/x-www-form-urlencoded

userName=test

###

POST http://localhost/LittleHoodAdvServer/API/sendSaveData HTTP/1.1
content-type: application/x-www-form-urlencoded

userId=1&stageType=stage1&clearTimeOriginal=16.461846&clearTimeH=0&clearTimeM=16&clearTimeS=02

###

POST http://localhost/LittleHoodAdvServer/API/getRank HTTP/1.1
content-type: application/x-www-form-urlencoded

stageType=stage1
###

POST http://localhost/LittleHoodAdvServer/API/getSaveData HTTP/1.1
content-type: application/x-www-form-urlencoded

userId=2